matrix:
    include:
        - os: linux
          dist: xenial
          language: python
          python: 3.7
        - os: osx
          language: generic
          env: PYTHON=3.7.3
before_install:
    - .travis/install.sh
    - source .travis/activate_virtualenv.sh
install:
    - pip install -e .
script:
    - pip install -r test-requirements.txt
    - pytest . --cov=.
after_script:
    - codecov
